
import type { EditorThemeClasses } from 'lexical';

export const editorTheme: EditorThemeClasses = {
  ltr: 'ltr',
  rtl: 'rtl',
  paragraph: 'mb-2',
  quote: 'ml-4 border-l-4 border-muted-foreground pl-4 italic',
  heading: {
    h1: 'text-3xl font-bold my-4',
    h2: 'text-2xl font-bold my-3',
    h3: 'text-xl font-bold my-2',
    h4: 'text-lg font-bold my-1',
    h5: 'text-base font-bold',
    h6: 'text-sm font-bold',
  },
  list: {
    nested: {
      listitem: 'ml-4',
    },
    ol: 'list-decimal list-inside my-2',
    ul: 'list-disc list-inside my-2',
  },
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    code: 'font-mono bg-muted p-1 rounded-sm text-sm',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
  },
  link: 'text-primary underline',
  code: 'bg-muted text-sm font-mono p-4 block rounded-md my-2 overflow-x-auto',
  codeHighlight: {
    'atrule': 'text-purple-500',
    'attr': 'text-purple-500',
    'boolean': 'text-red-500',
    'builtin': 'text-green-500',
    'cdata': 'text-gray-500',
    'char': 'text-green-500',
    'class': 'text-purple-500',
    'class-name': 'text-purple-500',
    'comment': 'text-gray-500',
    'constant': 'text-red-500',
    'deleted': 'text-red-500',
    'doctype': 'text-gray-500',
    'entity': 'text-red-500',
    'function': 'text-green-500',
    'important': 'font-bold',
    'inserted': 'text-green-500',
    'keyword': 'text-purple-500',
    'number': 'text-red-500',
    'operator': 'text-purple-500',
    'prolog': 'text-gray-500',
    'property': 'text-red-500',
    'punctuation': 'text-gray-500',
    'regex': 'text-red-500',
    'selector': 'text-green-500',
    'string': 'text-green-500',
    'symbol': 'text-red-500',
    'tag': 'text-red-500',
    'url': 'text-blue-500',
    'variable': 'text-green-500',
  },
};
